#! /bin/bash
alias bit="bash-it"
alias bith="bash-it help"
alias bits="bash-it show"
alias bite="bash-it enable"
alias bitd="bash-it disable"
alias bitha="bash-it help aliases"
alias bitsa="bash-it show aliases"
alias bitea="bash-it enable alias"
alias bitda="bash-it disable alias"
alias bithc="bash-it help completions"
alias bitsc="bash-it show completions"
alias bitec="bash-it enable completion"
alias bitdc="bash-it disable completion"
alias bithp="bash-it help plugins"
alias bitsp="bash-it show plugins"
alias bitep="bash-it enable plugin"
alias bitdp="bash-it disable plugin"