#! /bin/bash
alias bit="bash-it"
alias bith="bash-it help"
alias bits="bash-it show"
alias bite="bash-it enable"
alias bitd="bash-it disable"
alias bitha="bash-it help aliases"
alias bitsa="bash-it show aliases"
alias bitea="bash-it enable aliases"
alias bitda="bash-it disable aliases"
alias bithc="bash-it help completion"
alias bitsc="bash-it show completion"
alias bitec="bash-it enable completion"
alias bitdc="bash-it disable completion"
alias bithp="bash-it help plugins"
alias bitsp="bash-it show plugins"
alias bitep="bash-it enable plugins"
alias bitdp="bash-it disable plugins"