#! /bin/bash
alias gcs="git commit -v -s"
alias gcsm="git commit -v -sm"
alias gr="git rebase"
alias grp="git rebase -p"
alias grm="git remote"
alias grmao="git remote add origin"
alias grmau="git remote add upstream"
alias grmdel="git remote remove"
alias gts="git tag -s"